### ISSUE TITLE
Missing pre-generated netlists

### ISSUE THREAD

**Issue by jluebbe** [litex-hub/pythondata-cpu-vexriscv_smp#5]
When building from current https://github.com/litex-hub/linux-on-litex-vexriscv and https://github.com/litex-hub/litex-boards, the build fails if `sbt` is not available (see https://github.com/litex-hub/linux-on-litex-vexriscv/pull/230).

For example (based on https://github.com/jluebbe/linux-on-litex-vexriscv/actions/runs/847523090):

board | filename
-- | --
trellisboard | VexRiscvLitexSmpCluster_Cc1_Iw32Is4096Iy1_Dw32Ds4096Dy1_Ood_Wm
ecpix5 | VexRiscvLitexSmpCluster_Cc1_Iw32Is4096Iy1_Dw32Ds4096Dy1_Ood_Wm
ecpix5 4 core | VexRiscvLitexSmpCluster_Cc4_Iw64Is8192Iy2_Dw64Ds8192Dy2_Cdma_Ood_Wm
ecpix5 2 core with fpu | VexRiscvLitexSmpCluster_Cc2_Iw64Is8192Iy2_Dw64Ds8192Dy2_Cdma_Ood_Wm_Fpu4
de10nano | VexRiscvLitexSmpCluster_Cc1_Iw32Is4096Iy1_Dw32Ds4096Dy1_Ood_Wm

**Comment by Dolu1990** [comment]
Hi,

Basicaly, if you want to add new pregenerated configs, you can edit :
https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/vexriscv_smp/core.py#L172

And then run : 
https://github.com/litex-hub/pythondata-cpu-vexriscv_smp/blob/master/generate.py

This is where the name of the netlist is generated : 
https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/vexriscv_smp/core.py#L150

Then it should be all fine.

But maybe we should instead add sbt in the regression environnement ?
I mean, each of those netlist is quite heavyweight ^^

**Comment by jluebbe** [comment]
So would a PR adding the pregenerated configs needed by litex-boards be accepted in https://github.com/enjoy-digital/litex/? That would allow CI of those without pulling in the full `sbt` stack. @enjoy-digital, do you have an opinion on this?

**Comment by enjoy-digital** [comment]
@jluebbe: Lots of configurations are indeed now possible since the global cluster configuration comes from parameters exposed to the user (ex CPU count, AES, FPU, cache sizes) but also some parameters related to the hardware (DRAM data-width, use the wishbone interface, etc...). As said by @Dolu1990, each configuration is ~1MB for a single core, ~2.5MB for a quad-core so it will not be possible to add all configuration to this repository (this was by the way the reason SBT automatic install has been added to VexRiscv-SMP).

A reasonable compromise will be to provide at least the default configuration used by for LiteX-Boards and Linux-on-LiteX-Vexriscv for all boards (single core, no FPU, no AES) but with different DRAM data-width and use of Wishbone interface. I'm going to look at this.

**Comment by enjoy-digital** [comment]
https://github.com/litex-hub/pythondata-cpu-vexriscv_smp/commit/42569fbe536c35f8f4ba753ce7215a311f6cb142 adds the configuration that were missing when running python3 -m unittest test.test_build on Linux-on-LiteX-Vexriscv so this will allow building trellisboard, ecpix5 and de10nano without `sbt` installed. For the other configurations, sbt installation will still be required (for now, we'll see in the future if we add more configurations).

**Comment by jluebbe** [comment]
Thanks, I can now build bitstreams for the single CPU variants: https://github.com/jluebbe/linux-on-litex-vexriscv/actions/runs/853809065
